# URL do SharePoint a ser automatizado
WEBSITE=
# Nome de usuário para login
USUARIO=
# Senha do usuário para login
PALAVRA=
# Caminho para os documentos da prospecção
EVIDENCIAS=
# Caminho para a planilha da prospecção
PLANILHA=
