# Cspell: languages=pt,pt-BR
NOVO_REGISTRO_BTN=#botao_nova_solicitacao
MODAL_PROSPECCAO_DIV=#accordion-prospeccao
MODAL_GERENCIA_SEL=#gerencia
MODAL_COORDENA_SEL=#coordenacao
MODAL_PROSPECTOR_TXT=#prospectado_por
MODAL_EMPRESA_RDA=//*[@name='empresa']
MODAL_POSSUI_RO_RDA=//*[@name='possui_ro']
MODAL_CLIENTE_NOME_TXT=#nome_cliente
MODAL_CLIENTE_PN_TXT=#pn_cliente
MODAL_CLIENTE_CPF_TXT=#cpf_cliente
MODAL_ENDERECO_TXT=#endereco_cliente
MODAL_COMPLEMENTO_TXT=#complemento_cliente
MODAL_SUB-BAIRRO_TXT=#bairro_cliente
MODAL_REFERENCIA_TXT=#medidor_referencia_cliente
MODAL_ZONA-TRAFO_TXT=#zona_trafo
MODAL_TEMPO_MESES_TXT=#tempo_ocupacao
MODAL_INSTALACAO_CLASSE_RDA=//*[@name='classe']
MODAL_INSTALACAO_FASES_RDA=//*[@name='tipo']
MODAL_INSTALACAO_LOCAL_RDA=//*[@name='prospectado_por']
MODAL_FACHADA_FOTO_FILE=#file-fachada
MODAL_IRREGULAR_FOTO_FILE=#file-irregularidade
MODAL_DOCUMENTO_FOTO_FILE=#file-foto
MODAL_DOCUMENTO_TERMO_FILE=#file-regularizacao
MODAL_DOACAO_TERMO_FILE=#file-doacao
MODAL_SALVAR_BTN=//*[@id='botoes_form_principal']/button[2]
MODAL_PROSPECTOR_FORM=.needs-validation
